language: python
python:
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: lmrT2LYTHcp//Xk5/V48LZ1y9KGEnjyeyYP9OtskGVpOBhnF+rUcfu2fJKF/JmP2lY19jwOlclJ8kSmHjfxhWmVQqEW42LDfBfiwRyiOn8EfejMbZW7UfmMNJCquOxqE/8VmMi4QXVGedc8AaD5Hb/PXbzivEsQDRaXVyGbAbyP8NRWcIZ0/LjFldP12cT7T6tJWqfgxlqGuH2BRiP+VpMUiQPutejO2+dMm2dD/XAzur2YLLgqNIdWqFJqRxG2XUHqzuToXTAyi8oj/YLrA6BTrFcxTKRejN4qt/fKHZmk7E8lbRoBRrvHxZhyZRdUTqfvYBXrbzF8kSfJYhYrzQYyZNyEPkh2l6KN7ikY56ZTr5h6sKTCJqIRGR/cZf1EclpTslhrQZ0MKpc4AyOycugKoGA2VpZcwfgsbbuMv+UER6swbWoXJ7bOL+OW80wInWwQa3JjmDW8xJb44HgTMZcQtpsNaDdC58BtIijJUEB7Vne1STU7leBvKtD/HU3G4uanc8QaKPoFvuntM+o1qauIstmmh1sFzZbXK2t2Q1t2RioFdd7rM5Zq7d6hz/3DQSxTvfq2npyw+SJCyJuIOyEwxM7BU7SZz24CoKyAWozEfm88sEL5BfMFzC1reL3RiV4aIZYvP0k9iBOUsN+SFaBBnyG+pHq7U6+BOUXI817o=
  on:
    tags: true
    repo: kepsic/routeros_telegraf_exporter
    python: 3.8
